### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by timea-techgirl** [EliteAndroidApps/WhatsApp-Crypt12-Decrypter#2]
I'm getting this error.

But there are no problems with the key file. I checked with other apps.

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoa
der.java:58)
Caused by: java.security.InvalidKeyException: Illegal key size
        at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
        at javax.crypto.Cipher.init(Cipher.java:1393)
        at javax.crypto.Cipher.init(Cipher.java:1327)
        at decrypt12.decrypt12.decrypt(decrypt12.java:94)
        at decrypt12.decrypt12.main(decrypt12.java:146)
        ... 5 more

**Comment by EliteAndroidApps** [comment]
I'm unable to recreate the issue in order to investigate. Does this happen with the jar I provided or with your own compiled version? What version is your current JRE?

**Comment by timea-techgirl** [comment]
The problem was fixed when I used openjdk instead of Oracle. 

It was the jar you provided. 

Both jdks are on 1.8

**Comment by timea-techgirl** [comment]
WhatsApp is unable to decrypt the crypt12 file because of key file mismatch. The key is from the same account. I deleted the key file, installed whatsapp on a rooted device and the new key file didn't work either. I also used whatcrypt.com. 

Is whatsapp creating a new key file for each backup?

How to fix this? The keys are from the same whatsapp account and number.

**Comment by EliteAndroidApps** [comment]
The key file only usually changes if you physically re-install WhatsApp, although the cipher key can roll at any time. My own cipher key has not rolled for months so not sure what's going on there. Just grab the latest key and hope for the best I guess.

**Comment by timea-techgirl** [comment]
Other keys from the same account don't work. I can send you sample key files from the same account. It looks similar, just the ending has been changed when I viewed it on notepad++.

**Comment by timea-techgirl** [comment]
A footer is being added to the key files. I had this situation long ago with previous crypt versions and different key files had worked. I think whatsapp has changed it to make it more secure.

**Comment by timea-techgirl** [comment]
I have a solution though it's not good enough. If you install whatsapp and opt for restoring the history, the same key file is downloaded. If you don't opt for restoration, a different key is downloaded. 

Hope this helps you know what's going on.

**Comment by EliteAndroidApps** [comment]
Sometimes after you have restored WhatsApp from a backup, the key file gets replaced with a new cipher key (this does not always happen). To understand the data within the key file please take a look at: https://github.com/EliteAndroidApps/WhatsApp-Key-Generator which breaks everything down.

The key file does not contain a footer. The crypt12 database does contain a footer. The footer contains an md5 hash of the encrypted backup file (minus header / footer) and --nn (last two digits of cell number / whatsapp jid).

**Comment by timea-techgirl** [comment]
Oh, thank you. Will this help me get the key file that matches the database?

**Comment by ChrisSG** [comment]
Closed but a question for clarification: It does not seem that the footer contains a md5 of the database file after encrypting (excluding header and footer). Say the md5 of the bytes between the first 67 and the last 20 bytes. Version is 0xpp 0x01 0x02. Any info on this? Want to carve for WhatsApp backups...
