### ISSUE TITLE
Db Get Decrypted but requires password

### ISSUE THREAD

**Issue by ziadkiwan** [EliteAndroidApps/WhatsApp-Crypt12-Decrypter#5]
Dear Elite, thanks for the great effort i appreciate it ! well i installed everything and its working but when i decrypt the encrypted DB i get the encrypted DB file but a password is required and i noticed that the program is throwing the following error:
Fatal error:java.io.IOException: javax.crypto.AEADBadTagException: mac check in GCM failed
i don't know if its the problem but i just wanted to point it out, btw it works on Whatcrypt website, thank you!

**Comment by Rourke101** [comment]
I found the same error - have you solved it?
